# Generated by Django 5.0 on 2024-01-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist1', models.CharField(max_length=255)),
                ('artist2', models.CharField(max_length=255)),
                ('artist3', models.CharField(max_length=255)),
                ('date_of_inquiry', models.DateTimeField(verbose_name='date published')),
                ('vibe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='spotify_playlist.inquiry')),
            ],
        ),
    ]
