# Generated by Django 5.0 on 2024-01-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_playlist', '0002_spotifyuser_inquiry_spotify_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='spotify_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='spotify_playlist.spotifyuser'),
        ),
    ]
