# Generated by Django 5.0 on 2024-01-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_playlist', '0003_alter_inquiry_spotify_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='spotify_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
